#! /bin/bash
if git diff --exit-code --quiet
then
  for mod in bundle/*; do
    echo -e "\nUpdating $mod";
    cd $mod;
    git co master;
    git pull;
    version=$(echo $(git log -1 --oneline));
    cd ../..;
    if git diff --exit-code --quiet
    then
      echo "Nothing to commit"
    else
      git add $mod;
      git commit -m "updated module $mod to [$version]";
    fi
  done
else
  echo "Commit your changes before updating the modules"
fi
